# In wrangler.toml
name = "animepahe-api"
compatibility_date = "2024-04-05"

[pages]
# See https://developers.cloudflare.com/pages/platform/functions/configuration/#functions-compatibility-flags
compatibility_flags = ["nodejs_compat"]
